version: '3'

services:
  app:
    image: ruby:2.7.1
    command: irb
    working_dir: /app
    environment:
      - BUNDLE_PATH=/bundle
    volumes:
      - .:/app
      - bundle_path:/bundle

volumes:
  bundle_path:
